name: port-forward
base: core20
version: '0.1'
summary: Basic socat daemon
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict

apps:
  daemon:
    daemon: simple
    command: daemon.sh
    restart-condition: always
    install-mode: disable
    plugs:
      - network-bind

parts:
  socat:
    plugin: dump
    source: ./src
    stage-packages:
      - socat
      - iproute2
